version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=127.0.0.1,localhost

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

   mongo:
    image: mongo
    container_name: mongo
    restart: always
    # Username and password user for local development. Change to something suitable for production
    # Be sure to update __init__.py located in /flask/app when you change the username & password
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # Specify a local volume to store the db data & logging info
    volumes:
      - "~/container_volumes/mongo/data/db:/data/db"
      - "~/container_logs/mongo/log:/var/log/mongodb"
    ports:
      - 27017:27017
    depends_on:
      - app


volumes:
  static_data:
